#ifndef NW4R_PUBLIC_SND_H
#define NW4R_PUBLIC_SND_H

#include <nw4r/snd/adpcm.h>
#include <nw4r/snd/AxfxImpl.h>
#include <nw4r/snd/AxManager.h>
#include <nw4r/snd/AxVoice.h>
#include <nw4r/snd/BasicPlayer.h>
#include <nw4r/snd/BasicSound.h>
#include <nw4r/snd/Channel.h>
#include <nw4r/snd/debug.h>
#include <nw4r/snd/DisposeCallbackManager.h>
#include <nw4r/snd/DvdSoundArchive.h>
#include <nw4r/snd/EnvGenerator.h>
#include <nw4r/snd/FrameHeap.h>
#include <nw4r/snd/FxBase.h>
#include <nw4r/snd/FxReverbHi.h>
#include <nw4r/snd/global.h>
#include <nw4r/snd/InstancePool.h>
#include <nw4r/snd/Lfo.h>
#include <nw4r/snd/MemorySoundArchive.h>
#include <nw4r/snd/MmlParser.h>
#include <nw4r/snd/MmlSeqTrack.h>
#include <nw4r/snd/MmlSeqTrackAllocator.h>
#include <nw4r/snd/MoveValue.h>
#include <nw4r/snd/NandSoundArchive.h>
#include <nw4r/snd/NoteOnCallback.h>
#include <nw4r/snd/PlayerHeap.h>
#include <nw4r/snd/SeqPlayer.h>
#include <nw4r/snd/SeqSound.h>
#include <nw4r/snd/SeqSoundHandle.h>
#include <nw4r/snd/SeqTrack.h>
#include <nw4r/snd/SeqTrackAllocator.h>
#include <nw4r/snd/SoundArchive.h>
#include <nw4r/snd/SoundArchiveFile.h>
#include <nw4r/snd/SoundArchivePlayer.h>
#include <nw4r/snd/SoundHandle.h>
#include <nw4r/snd/SoundHeap.h>
#include <nw4r/snd/SoundInstanceManager.h>
#include <nw4r/snd/SoundMemoryAllocatable.h>
#include <nw4r/snd/SoundPlayer.h>
#include <nw4r/snd/SoundStartable.h>
#include <nw4r/snd/SoundSystem.h>
#include <nw4r/snd/SoundThread.h>
#include <nw4r/snd/StrmChannel.h>
#include <nw4r/snd/StrmFile.h>
#include <nw4r/snd/StrmPlayer.h>
#include <nw4r/snd/StrmSound.h>
#include <nw4r/snd/Task.h>
#include <nw4r/snd/Util.h>
#include <nw4r/snd/Voice.h>
#include <nw4r/snd/WaveFile.h>
#include <nw4r/snd/WaveSound.h>
#include <nw4r/snd/WsdPlayer.h>

#endif
